### ISSUE TITLE
Export attribute

### ISSUE THREAD

**Issue by pashajanx** [ikenfin/fo-csv#1]
Добрый день, подскажите пожалуйста, если в данным момент возможность экспортировать атрибуты?

**Comment by ikenfin** [comment]
Привет! 
Сорри за долгое молчание.
Такую возможность пока не реализовал, но она есть в планах. Думаю либо к концу января фича появится, либо уже в феврале - хочу сделать её расширяемой и дополняемой аналогично как это в импорте реализовано.

**Comment by ikenfin** [comment]
Привет @pashajanx !
В последнем [релизе](https://github.com/Freeocart/fo-csv/releases/tag/v0.0.98) реализовал поддержку экспорта атрибутов и три встроенных энкодера - два advantshop-like и колоночный.
