### ISSUE TITLE
Модуль не импортирует

### ISSUE THREAD

**Issue by AskhatBi** [ikenfin/fo-csv#28]
Добрый вечер Сергей,
Нашел ваш модуль по импорту и экспорту товара через CSV файл, очень полезный и функциональный, спасибо за это! Начал тестировать, но почему то не идет процесс импорта. Сможете глянуть на CSV файл и скриншот настройки, буду очень благодарен. 
Сайт на OpenServer. Загрузил скрин CSV файла или можете посмотреть по ссылке inur.kz/products3.csv
![focsv-screenshot](https://user-images.githubusercontent.com/82103984/113882247-f2faf900-97de-11eb-9dc0-a4e4c339e914.PNG)
![csv-file](https://user-images.githubusercontent.com/82103984/113882544-32c1e080-97df-11eb-8cab-0d48cb9e6e48.PNG)

**Comment by ikenfin** [comment]
@AskhatBi Привет! Сорри, только сейчас увидел Ваше ишью. 😔 

Нужно проверить что в логах (хранится в `*/storage/logs/foc_csv_importer.txt`) чтобы сказать точнее. Но скорее всего проблема с ключевым полем (model) - там были проблемы с этим в случаях когда есть несколько товаров с одинаковым model.

**Comment by AskhatBi** [comment]
Спасибо, пробовал несколько вещей и точно не знаю что помогло, но все работает идеально. Огромное спасибо, сэкономил кучу времени. Сложно ли еще добавить опции, SEO url и схожие товары?

**Comment by ikenfin** [comment]
В ближайшее время планов на обновления этого модуля нету, но все желающие могут предлагать свои дополнения с помощью PR
