### ISSUE TITLE
Выдает ошибку, в чем может быть проблема?

### ISSUE THREAD

**Issue by AskhatBi** [ikenfin/fo-csv#34]
Добрый вечер,
выдает ошибку "Ошибка во время отправки данных!".
Последний раз вы просили лог, нашел пункт показать состояние.
{"profiles":{"default":{"encoding":"cp1251","csvFieldDelimiter":";","categoryDelimiter":"/","categoryLevelDelimiter":">>","defaultAttributesGroup":"Характеристики","keyField":"product:model","skipLines":0,"bindings":{"product_description:name":0,"product:model":1,"category_description:name":2},"importMode":"updateCreate","imagesImportMode":"add","csvImageFieldDelimiter":";","previewFromGallery":true,"processAtStepNum":20,"removeCharsFromCategory":"[]{}","removeManufacturersBeforeImport":false,"csvWithoutHeaders":false,"csvHeadersLineNumber":1,"statusRewrites":[],"stockStatusRewrites":[],"downloadImages":false,"store":null,"language":"1","skipLineOnEmptyFields":[],"multicolumnFields":[],"replaceAttributes":false,"attributeParser":null,"attributeParserData":[]}},"keyFields":["product:product_id","product:sku","product:model","product_description:name","product:ean","product:mpn","product:jan","product:isbn"],"attributeParsers":{"advantshop":{"title":"Атрибуты в формате Advantshop","options":{"keyvalue_delimiter":{"title":"Символ разделитель ключей и значений","default":":"},"entries_delimiter":{"title":"Символ разделитель атрибутов","default":";"}}},"advantshop_grouped":{"title":"Сгруппированные атрибуты в формате Advantshop","options":{"groupattrs_delimiter":{"title":"Символ разделитель между группой и списком значений","default":"=>"},"groups_delimiter":{"title":"Символ разделитель между группами","default":","},"keyvalue_delimiter":{"title":"Символ разделитель ключей и значений","default":":"},"entries_delimiter":{"title":"Символ разделитель атрибутов","default":";"}}},"column":{"title":"Атрибуты в колонках","options":{"columns":{"title":"Колонка","default":[],"type":"column"}}}},"encodings":["none","UTF8","cp1251"],"dbFields":{"product":{"0":"product_id","1":"model","2":"sku","3":"upc","4":"ean","5":"jan","6":"isbn","7":"mpn","9":"quantity","10":"stock_status_id","11":"image","14":"price","17":"date_available","18":"weight","20":"length","21":"width","22":"height","27":"status","28":"viewed"},"product_description":{"2":"name","3":"description","4":"tag","5":"meta_title","6":"meta_h1","7":"meta_description","8":"meta_keyword"},"product_image":{"2":"image"},"product_special":{"4":"price","5":"date_start","6":"date_end"},"manufacturer":["manufacturer_id","name","image"],"category":{"0":"category_id","1":"image","6":"status"},"category_description":{"2":"name","3":"description","4":"meta_title","5":"meta_h1","6":"meta_description","7":"meta_keyword"}},"stores":[{"name":"Магазин сантехники в Алматы","id":null}],"stock_statuses":[{"id":"7","name":"В наличии"},{"id":"5","name":"Нет в наличии"},{"id":"6","name":"Ожидание 2-3 дня"},{"id":"8","name":"Предзаказ"}],"statuses":[{"id":0,"name":"Отключено"},{"id":1,"name":"Включено"}],"languages":[{"name":"Russian","id":"1"}],"csvFileRef":{},"csvFields":["Название","Модель","Категория","Бренд","к-во","статус","meta-title","meta-description","описание","фото","Сорт","Цена","Характеристики"]}

**Comment by ikenfin** [comment]
Привет! Нужен именно лог-файл, его можно найти в папке где установлен opencart (папка **system/logs/**, для opencart 2 или **папка_storage_настроенная_в_opencart/logs**, для opencart 3), файл называется _foc_csv_importer.txt_ или _foc_csv_exporter.txt_, для импортёра и экспортёра соответственно)
