### ISSUE TITLE
can you add some commet for how to used it.

### ISSUE THREAD

**Issue by sky00781** [ikenfin/fo-csv#45]
hello,i have download  version 1.03 package and install it. but i can not find any menu for it ,can you please add how to used it

**Comment by ikenfin** [comment]
Hello!
After module was installed you should activate it from modules page (*left panel: Extensions -> Extensions -> [ select "Modules" in dropdown ] -> locate "FOC: Flexible CSV import/export" and press "Activate" green button*). 

After module was activated, you can open import/export interface using edit blue button. Also you can locate quick link at left menu in Maintenance section (appears after activate and page refresh)
